//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomInformation()
        {
            this.DiscountRooms = new HashSet<DiscountRoom>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.RoomImage2 = new HashSet<RoomImage2>();
            this.RoomServiceAndFacilities = new HashSet<RoomServiceAndFacility>();
        }
    
        public int RoomID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> RoomType { get; set; }
        public string RoomNameCN { get; set; }
        public string RoomNameEN { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<bool> CanAddBed { get; set; }
        public Nullable<bool> OfferBreakfast { get; set; }
        public Nullable<bool> PermitSmoking { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountRoom> DiscountRooms { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomImage2> RoomImage2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomServiceAndFacility> RoomServiceAndFacilities { get; set; }
    }
}
