//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAndFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceAndFacility()
        {
            this.HotelServiceAndFacilities = new HashSet<HotelServiceAndFacility>();
            this.RoomServiceAndFacilities = new HashSet<RoomServiceAndFacility>();
        }
    
        public int ServiceFacilityID { get; set; }
        public string ServiceFacilityCHName { get; set; }
        public string ServiceFacilityENName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelServiceAndFacility> HotelServiceAndFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomServiceAndFacility> RoomServiceAndFacilities { get; set; }
    }
}
